[project]
name = "deepru-test"
version = "0.0.1"
description = "Test task deepru"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "uvicorn>=0.34.2",
]
